src/Entity/Product.php
<?php

//declare(strict_types = 1);

namespace App\Entity;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\GeneratedValue;
use Doctrine\ORM\Mapping\Id;
use Doctrine\ORM\Mapping\JoinColumn;
use Doctrine\ORM\Mapping\ManyToMany;
use Doctrine\ORM\Mapping\ManyToOne;
use Doctrine\ORM\Mapping\Table;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Validator\Constraints\Range;

#[Entity]
#[Table(name: 'products')]
class Product
{
    #[Id]
    #[GeneratedValue(strategy: 'AUTO')]
    #[Column(name: 'id', type: 'integer')]
    private int $id;

    #[ManyToOne(targetEntity: ProductCategory::class)]
    #[JoinColumn(name: 'category_id', referencedColumnName: 'id', nullable: false, onDelete: 'RESTRICT')]
    private ProductCategory $category;

    #[Column(name: 'title', type: 'string', length: 100)]
    #[NotBlank]
    #[Length(max: 100)]
    private string $title;
    #[Column(name: 'sub_title', type: 'string', length: 100)]
    #[NotBlank]
    #[Length(max: 100)]
    private string $subTitle;

    #[Column(name: 'ingredients', type: 'string', length: 1000)]
    #[NotBlank]
    #[Length(max: 1000)]
    private string $ingredients;

    #[Column(name: 'price', type: 'float', precision: 6, scale: 2)]
    #[NotBlank]
    #[Range(min: 0)]
    private float $price;

    #[Column(name: 'weight', type: 'integer')]
    #[Range(min: 0)]
    private int $weight;

    #[Column(name: 'calories', type: 'integer')]
    #[Range(min: 0)]
    private int $calories;

    #[Column(name: 'priority', type: 'integer')]
    private int $priority = 0;

    #[Column(name: 'image_path', type: 'string')]
    #[NotBlank]
    private string $imagePath;

    public function getId(): int
    {
        return $this->id;
    }

    public function setCategory(ProductCategory $category): void
    {
        $this->category = $category;
    }

    public function getCategory(): ProductCategory
    {
        return  $this->category;
    }

    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    public function getTitle(): string
    {
        return $this->title;
    }

    public function setSubTitle(string $subTitle): void
    {
        $this->subTitle = $subTitle;
    }

    public function getSubtitle(): string
    {
        return $this->subTitle;
    }

    public function setIngredients(string $ingredients): void
    {
        $this->ingredients = $ingredients;
    }

    public function getIngredients(): string
    {
        return $this->ingredients;
    }

    public function setPrice(float $price): void
    {
        $this->price = $price;
    }

    public function getPrice(): float
    {
        return $this->price;
    }

    public function setWeight(int $weight): void
    {
        $this->weight = $weight;
    }

    public function getWeight(): int
    {
        return $this->weight;
    }

    public function setCalories(int $calories): void
    {
        $this->calories = $calories;
    }

    public function getCalories(): ?int
    {
        return $this->calories;
    }

    public function getPriority(): int
    {
        return $this->priority;
    }

    public function setPriority(int $priority): void
    {
        $this->priority = $priority;
    }

    /**
     * @param string $imagePath
     */
    public function setImagePath(string|UploadedFile|null $imagePath): void
    {

        if ($imagePath instanceof UploadedFile) {
            $name = \md5(\uniqid());
            $extension = $imagePath->getClientOriginalExtension();
            $fileName = $name.'.'.$extension;

            $uploadsDir =__DIR__.'/../../public/uploads';


            $imagePath->move($uploadsDir, $fileName);
            $imagePath = '/uploads/'.$fileName;
        }

        if ($imagePath) {
            $this->imagePath = $imagePath;
        }
    }

    /**
     * @return string
     */
    public function getImagePath(): File
    {
        $publicDir = __DIR__.'/../../public';
        $imagePath = $publicDir.$this->imagePath;

        $file = new File($imagePath, false);
        return $file;
    }

    public function  getWebImagePath(): string
    {
        return $this->imagePath;
    }
}

templates/html-layout.html.twig
<html lang="en">
<head>
    <title>
        {% block title %}Felichita{% endblock %}
    </title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <link href="/css/main.css" rel="stylesheet">
</head>

<body>
{% block body%}
{% endblock %}
</body>
</html>

templates/main-page.html.twig
{% extends 'html-layout.html.twig' %}

{% block body %}
    <div class="container-fluid pt-5">
        <div class="row">
            <div class="col-2">
                <ul class="menu-categories">
                    {% for category in categories %}
                    <li>{{ category.title }}</li>
                    {% endfor %}
                </ul>
             </div>
            <div class="col-10">
                {% for group in grouped_products %}
                    <div class="pt-3 bt-3 border-bottom product-category">
                        <div class="row">
                            {% for product in group.products %}
                                <div class="col-4">
                                    <div class="row align-item-center">
                                        <div class="col-3 text-center">
                                            <img width="64" src="{{ product.webImagePath }}"/>
                                        </div>

                                        <div class="col-6">
                                            <h5>{{ product.title }}</h5>

                                            <div class="fw-bolder">{{ product.subTitle }}</div>

                                            <div class="text-muted small-text-center">{{ product.ingredients }}</div>
                                        </div>

                                        <div class="col-3 text-end">
                                            <div class="fb-bolder">{{ product.price }} UAH</div>
                                            <div class="text-muted">{{ product.weight }} g</div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}